name: Automated Testing

on:
  push:

permissions:
  contents: read

jobs:
  composer:
    name: Validate composer files
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - lock-version: 3.9

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  composer-require-checker:
    name: Check composer requirements
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - uses: ./.github/actions/setup-composer
      - uses: ./.github/actions/setup-phive

      - name: Check composer requirements
        run: composer require-check

  composer-unused:
    name: Check unused composer requirements
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - uses: ./.github/actions/setup-composer
      - uses: ./.github/actions/setup-phive

      - name: Check unused composer requirements
        run: composer unused

  cs-fixer:
    name: Check code style with CS Fixer
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - uses: ./.github/actions/setup-composer
      - uses: ./.github/actions/setup-phive

      - name: Check code style
        run: composer cs-fixer-check -- --show-progress=none


  phpcs:
    name: Check code style with PHP Code Sniffer
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - uses: ./.github/actions/setup-composer

      - name: Check code style
        run: composer phpcs
